name: Build an run tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build-and-test:
    name: Build an run tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run CI script
        run: npm run ci

      - name: Run tests
        run: PK_1=556863b01e01906d378a1278639c26c5675342aa3deebe6997b477d63e74221e npm run test
